# Generated by Django 2.0.3 on 2018-03-12 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Content', models.CharField(max_length=100, verbose_name='错误信息')),
            ],
            options={
                'ordering': ['NO'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('APPName', models.CharField(max_length=100, verbose_name='APP名称')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块汇总',
            },
        ),
        migrations.CreateModel(
            name='ModuleAuthority',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('Mark', models.CharField(max_length=255, verbose_name='代号')),
                ('Note', models.CharField(blank=True, default=None, max_length=255, verbose_name='说明')),
                ('Module', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块')),
            ],
            options={
                'verbose_name': '模块权限',
                'verbose_name_plural': '模块权限汇总',
            },
        ),
        migrations.CreateModel(
            name='ModuleInterface',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, verbose_name='名称')),
                ('URL', models.CharField(max_length=255, verbose_name='入口地址')),
                ('Json_Request', models.CharField(blank=True, default=None, max_length=255, verbose_name='提交JSON样例')),
                ('Json_Success', models.CharField(blank=True, default=None, max_length=255, verbose_name='返回JSON样例')),
                ('Note', models.CharField(blank=True, default=None, max_length=255, verbose_name='说明')),
                ('Module', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块')),
            ],
            options={
                'verbose_name': '模块接口',
                'verbose_name_plural': '模块接口汇总',
            },
        ),
        migrations.CreateModel(
            name='ModuleMenu',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Display_ICO', models.CharField(max_length=100, verbose_name='图标')),
                ('Display_Name', models.CharField(max_length=100, verbose_name='名称')),
                ('URL', models.CharField(max_length=255, verbose_name='入口地址')),
                ('Module', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='general.Module', verbose_name='模块')),
                ('P_Menu', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='general.ModuleMenu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '模块菜单',
                'verbose_name_plural': '模块菜单汇总',
                'ordering': ['Display_ICO'],
            },
        ),
    ]
