# Generated by Django 2.0.3 on 2018-03-12 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdm', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Status',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型汇总',
            },
        ),
        migrations.CreateModel(
            name='PartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('QR_Code', models.CharField(blank=True, max_length=256, null=True, verbose_name='二维码')),
                ('Part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdm.Part', verbose_name='零件')),
            ],
            options={
                'ordering': ['Part__ItemNO'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200, verbose_name='名称')),
                ('Tell', models.CharField(max_length=200, verbose_name='电话')),
                ('Address', models.CharField(blank=True, max_length=100, null=True, verbose_name='地址')),
                ('Company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org.Company', verbose_name='公司')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
        migrations.CreateModel(
            name='Store_Status',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NO', models.CharField(max_length=20, unique=True, verbose_name='代码')),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型汇总',
                'ordering': ['NO'],
            },
        ),
        migrations.CreateModel(
            name='StoreCon',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Status', models.CharField(blank=True, max_length=100, null=True, verbose_name='状态')),
                ('isActive', models.BooleanField(default=True, verbose_name='是否生效')),
                ('Head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HeadStore', to='store.Store', verbose_name='上一级仓库')),
                ('Last', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LastStore', to='store.Store', verbose_name='下一级仓库')),
            ],
            options={
                'ordering': ['Head'],
            },
        ),
        migrations.CreateModel(
            name='StoreConPartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Number', models.IntegerField(default=0, verbose_name='数量')),
                ('PartLive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.PartLive', verbose_name='物料')),
                ('Store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store', verbose_name='仓库')),
            ],
            options={
                'ordering': ['PartLive__Part__ItemNO'],
            },
        ),
        migrations.CreateModel(
            name='StoreForm',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20, verbose_name='名称')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('OriginStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OriginStore', to='store.Store', verbose_name='仓库')),
                ('Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Form_Status', verbose_name='类型')),
                ('TargetStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TargetStore', to='store.Store', verbose_name='目标仓库')),
            ],
            options={
                'ordering': ['OriginStore'],
            },
        ),
        migrations.CreateModel(
            name='StoreFormConPartLive',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Number', models.IntegerField(default=0, verbose_name='数量')),
                ('PartLive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.PartLive', verbose_name='物料')),
                ('StoreForm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.StoreForm', verbose_name='表单')),
            ],
            options={
                'ordering': ['StoreForm'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store_Status', verbose_name='类型'),
        ),
    ]
